erDiagram
    PERSONNE ||--o| BENEVOLE : "peut etre"
    PERSONNE {
        int id_personne PK
        varchar nom
        varchar prenom
        varchar telephone
        varchar email
        boolean est_adherent
    }
    BENEVOLE {
        int id_personne PK,FK
        date date_entree
        boolean est_actif
    }
