erDiagram
    CATEGORIE ||--o{ OBJET : "classe (RG4)"
    CATEGORIE {
        int id_categorie PK
        varchar libelle UK "mobilier, electromenager..."
    }
    OBJET {
        int id_objet PK
        varchar etiquette UK
        varchar designation
        int poids_g
        enum etat_arrivee "bon_etat | a_reparer | hors_service (RG5)"
        enum statut "arrive | en_reparation | en_rayon | vendu | recycle (RG6)"
        numeric prix_affiche
        date date_mise_en_rayon
        int id_categorie FK "NOT NULL"
    }
