services:
  db:
    image: postgres:16
    container_name: laremise_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: remise
      POSTGRES_PASSWORD: remise
      POSTGRES_DB: laremise
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: